export const STORE_URL_MATCH = "STORE_URL_MATCH";
export const GET_URL_MATCH_LIST = "GET_URL_MATCH_LIST";
export const DETECT_SCREEN = "DETECT_SCREEN";
export const SET_SCREEN = "SET_SCREEN";
export const SHORTEN_URL = "SHORTEN_URL";
